version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: node.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
      build: 
        context: .
        dockerfile: node.Dockerfile
      volumes:
        - /app/node_modules
        - .:/app
      command: ["npm run test"] 